"""Append the three remaining Minor Arcana suits (Cups, Swords, Pentacles)
to data/tarot_corpus.json. Runs once; idempotent if the existing rows
already cover them (skips duplicates by (card_id, orientation))."""
from __future__ import annotations

import json
from pathlib import Path

CORPUS_PATH = Path(__file__).resolve().parent.parent / "data" / "tarot_corpus.json"


def expand_suit(rows):
    out = []
    for cid, zh, en, themes, imagery, ups, downs in rows:
        out.append({
            "card_id": cid, "zh": zh, "en": en, "orientation": "upright",
            "themes": themes, "imagery": imagery, "situations": ups,
            "keywords": themes[:5],
        })
        out.append({
            "card_id": cid, "zh": zh, "en": en, "orientation": "reversed",
            "themes": [f"逆位·{t}" for t in themes],
            "imagery": imagery + " (逆位)",
            "situations": downs,
            "keywords": [f"反{t}" for t in themes[:5]],
        })
    return out


# ── CUPS (Water / Emotion) — ids 36-49 ──
CUPS = [
    (36, "圣杯一", "Ace of Cups",
     ["情感泉源", "新爱开启", "心灵丰盈"],
     "云中之手托起一杯圣水，鸽子衔圣饼降下——情感的纯然涌起。",
     {"career": "对工作重新有热情，或一份能感动你的新机会出现。",
      "relationship": "新感情萌生，或一段关系重新被温柔注满。",
      "health": "情绪正在自愈，眼泪是一种清洗。",
      "growth": "允许自己再次被打动。心打开来了。"},
     {"career": "对工作的热情干涸——已经麻木一段时间了。",
      "relationship": "压抑情感、用工作掩盖空缺。",
      "health": "长期紧绷，情绪没出口。",
      "growth": "情感开关被你关掉了，重新打开需要练习。"}),
    (37, "圣杯二", "Two of Cups",
     ["伙伴关系", "互信", "灵魂呼应"],
     "男女举杯相对——平等而真诚的交换。",
     {"career": "一段重要合作或搭档关系。彼此能给对方提供互补的价值。",
      "relationship": "深度的互相欣赏。可能是新关系，也可能是关系中的和解。",
      "health": "和某个支持者(伴侣、好友、教练)一起调整身体。",
      "growth": "学会承认我需要某个人。"},
     {"career": "合作关系开始失衡，或者沟通断了。",
      "relationship": "误会和未表达的情绪堆积。",
      "health": "孤军奋战，缺乏支持。",
      "growth": "孤立感不是力量。承认需要别人需要勇气。"}),
    (38, "圣杯三", "Three of Cups",
     ["庆贺", "友情", "群体喜悦"],
     "三位女子举杯共舞——丰收的庆典。",
     {"career": "团队成果值得集体庆祝。",
      "relationship": "进入有朋友圈支持的阶段，关系不再是孤岛。",
      "health": "通过社交活动恢复活力。",
      "growth": "你的喜悦在被分享时翻倍。"},
     {"career": "团队表面热闹但暗潮汹涌。或者你独自庆祝。",
      "relationship": "把社交场合当成关系的替代——人多但不深。",
      "health": "聚会饮酒过度，事后更累。",
      "growth": "区分热闹和真正的连接。"}),
    (39, "圣杯四", "Four of Cups",
     ["冷漠", "对眼前不满", "错过赠予"],
     "树下盘坐的人无视云中递来的杯——已有的不被看见。",
     {"career": "对当下的机会缺乏热情，明明手上有的没看见。",
      "relationship": "感情进入倦怠期，对方依然在身边但你没感觉。",
      "health": "对身体的小好转视而不见，只盯着没好的部分。",
      "growth": "感恩练习不是矫情，是看见已有的。"},
     {"career": "终于注意到那个被忽视的机会。",
      "relationship": "重新看见对方的好。",
      "health": "意识到自己有多久没好好对身体了。",
      "growth": "醒过来。重新参与生活。"}),
    (40, "圣杯五", "Five of Cups",
     ["哀悼", "失去", "盯着倒下的三杯"],
     "黑袍人低头看打翻的三杯，身后还有两杯——只盯着失去的。",
     {"career": "为一次失败、被裁、项目失败而难过。但还有两杯没倒。",
      "relationship": "失去后无法走出，可能是分手、离婚、亲人。",
      "health": "为一次疾病的损失沉湎。",
      "growth": "允许哀悼。但也别忘还站着的两杯。"},
     {"career": "终于回头看见还在的资源。",
      "relationship": "走出失恋，开始接受新的可能。",
      "health": "停止沉浸于过去的我，接纳现在的身体。",
      "growth": "宽恕——别人和自己。"}),
    (41, "圣杯六", "Six of Cups",
     ["怀旧", "童年回忆", "纯真的赠予"],
     "两个孩子在花园中递杯——天真的赠与时光。",
     {"career": "和老同事/老客户重逢，旧关系带来新机会。",
      "relationship": "和初恋、童年伙伴重连，或者关系回到最初的甜。",
      "health": "童年的习惯(晒太阳、跑步、玩耍)能治愈现在的你。",
      "growth": "找回那个还没被磨损的自己。"},
     {"career": "活在过去的成功里，不愿适应现在。",
      "relationship": "对过去的人难以放下，新关系进不来。",
      "health": "回到不健康的童年模式——比如用糖安慰自己。",
      "growth": "怀旧是温柔的陷阱。"}),
    (42, "圣杯七", "Seven of Cups",
     ["幻想", "太多选项", "白日梦"],
     "云中浮现七杯各有不同——城堡、珠宝、龙、骷髅——真假混杂。",
     {"career": "想做的事太多，没一个落地。",
      "relationship": "对几个人都有好感，无法专一选择。",
      "health": "在各种健康偏方间换来换去。",
      "growth": "区分真实的渴望和被诱惑的幻象。"},
     {"career": "终于落地选一件。",
      "relationship": "认清谁是真，谁是幻。",
      "health": "回归一两个真正有效的方法。",
      "growth": "幻想散了，看到了真正想要的。"}),
    (43, "圣杯八", "Eight of Cups",
     ["主动离开", "走向更深", "舍弃已得"],
     "持杖人背对八杯走向月夜——已得不再够。",
     {"career": "放下表面成功的工作去追真正想做的。",
      "relationship": "主动结束一段已经空了的关系。",
      "health": "离开伤害你的环境——比如不健康的家庭氛围。",
      "growth": "你已经知道更深的在哪。出发就是。"},
     {"career": "想走但又留——纠结消耗最大。",
      "relationship": "明知该结束但不甘心。",
      "health": "知道要改但回到老路。",
      "growth": "犹豫比离开更疼。"}),
    (44, "圣杯九", "Nine of Cups",
     ["满足", "心愿达成", "知足的喜悦"],
     "九杯弧形排列，肥满男子坐前——他的心愿已成。",
     {"career": "项目让你由衷满意。",
      "relationship": "关系让你感到满足而非匮乏。",
      "health": "身体进入舒适状态。",
      "growth": "允许自己感觉够了。"},
     {"career": "表面满足，内里空虚。",
      "relationship": "得到了想要的却发现不是真正想要的。",
      "health": "舒适过头——开始懒散。",
      "growth": "重新校准什么是真满足。"}),
    (45, "圣杯十", "Ten of Cups",
     ["家庭圆满", "彩虹般的幸福", "情感的归宿"],
     "一家人面向彩虹下的十杯——情感旅程的圆环。",
     {"career": "工作和家庭达到平衡，归属感强。",
      "relationship": "组建家庭、稳定共生的阶段。",
      "health": "身心和家人都在好的状态。",
      "growth": "你已经找到家。"},
     {"career": "事业占了家庭的位置，归属感缺。",
      "relationship": "家庭表面和睦但裂缝存在。",
      "health": "为家庭牺牲健康。",
      "growth": "家的意义需要重新校准。"}),
    (46, "圣杯侍从", "Page of Cups",
     ["纯真的情感", "灵感", "可爱的奇思"],
     "持杯人发现杯中一条鱼——意外的灵感跃出。",
     {"career": "新创意冒出，可能从最意外的地方。",
      "relationship": "可爱的小信号——一句话、一个动作让你心动。",
      "health": "用玩乐的方式照顾身体。",
      "growth": "允许内在的小孩说话。"},
     {"career": "情绪化反应影响判断。",
      "relationship": "幼稚或被对方的幼稚困扰。",
      "health": "情绪化进食或拒食。",
      "growth": "区分内在小孩的智慧和闹脾气。"}),
    (47, "圣杯骑士", "Knight of Cups",
     ["浪漫追求", "理想主义", "情感驱动"],
     "持杯白马骑士缓步——理想化的求爱姿态。",
     {"career": "为理想驱动而非现实主义。",
      "relationship": "浪漫的追求者出现，或你成为那个追求者。",
      "health": "情绪驱动你的运动或饮食选择。",
      "growth": "情感是好的方向，但还需现实落地。"},
     {"career": "情绪化决策。",
      "relationship": "追求者只在追求本身——一旦得到就失去兴趣。",
      "health": "情绪起伏影响身体。",
      "growth": "区分爱本身和爱正在恋爱的感觉。"}),
    (48, "圣杯圣母", "Queen of Cups",
     ["共情", "情感深度", "直觉之母"],
     "海边王座的女性凝视圣杯——情感的深井。",
     {"career": "用共情能力做人际工作很有优势。",
      "relationship": "你能给予深度情感支持。",
      "health": "你已经能感知身体细微的信号。",
      "growth": "你的敏感是天赋而非软弱。"},
     {"career": "把别人的情绪扛成自己的——耗尽。",
      "relationship": "情绪过载，被他人感受淹没。",
      "health": "情绪化吃喝、失眠、躯体化。",
      "growth": "建立情感边界，共情不等于背负。"}),
    (49, "圣杯国王", "King of Cups",
     ["情感成熟", "稳定的同理心", "海中的智者"],
     "海中王座，王手持杯——汹涌情感中的稳定者。",
     {"career": "在情绪混乱的局面中你是定海针。",
      "relationship": "你能稳稳容纳对方的所有情绪。",
      "health": "情绪管理已经成熟。",
      "growth": "你不再被情绪卷走。"},
     {"career": "情感操纵，或被人情感操纵。",
      "relationship": "表面平静，底下汹涌。",
      "health": "压抑情绪久了出现身体症状。",
      "growth": "稳定不是压抑。让海有时翻。"}),
]


# ── SWORDS (Air / Mind) — ids 50-63 ──
SWORDS = [
    (50, "宝剑一", "Ace of Swords",
     ["清晰", "突破", "真相之剑"],
     "云中之手握剑顶王冠，胜利之锐——思维的纯净突破。",
     {"career": "一个清晰的新观点或决策的瞬间。",
      "relationship": "终于把心里那句话说出来了，关系进入真实。",
      "health": "诊断终于明确，方向定了。",
      "growth": "看清是最大的力量。"},
     {"career": "决断不够，或者用言语伤人。",
      "relationship": "话太尖，对方受伤。",
      "health": "用过激的方式纠正习惯。",
      "growth": "锋利需要方向。"}),
    (51, "宝剑二", "Two of Swords",
     ["僵局", "蒙眼平衡", "拒绝看见"],
     "蒙眼女性双剑交叉胸前——选择被悬置。",
     {"career": "两个选项卡住，谁都不愿选。",
      "relationship": "对关系的问题选择性失明。",
      "health": "拒绝面对一个检查结果。",
      "growth": "蒙住眼睛不会让选择消失。"},
     {"career": "终于摘下蒙布做决定。",
      "relationship": "压抑的问题终于被说出。",
      "health": "面对那个一直回避的诊断。",
      "growth": "看见是改变的第一步。"}),
    (52, "宝剑三", "Three of Swords",
     ["心痛", "背叛", "言语之伤"],
     "三剑穿心，乌云密布——情感的直接刺穿。",
     {"career": "一次严厉的批评或被拒绝。",
      "relationship": "背叛、分手、亲人的指责。",
      "health": "身心被一次打击撕开。",
      "growth": "痛是真实的。允许它存在，不要急着翻篇。"},
     {"career": "终于从那次打击中爬起来。",
      "relationship": "结束哀悼，准备再次开放。",
      "health": "康复进入新阶段。",
      "growth": "你比想象中能承受。"}),
    (53, "宝剑四", "Four of Swords",
     ["休整", "暂停", "卧床冥想"],
     "石棺上长眠的骑士，三剑悬墙——主动撤退恢复。",
     {"career": "需要休假或退一线。再不停就要垮。",
      "relationship": "关系需要暂停而非进展。",
      "health": "卧床、睡足、什么都不做。",
      "growth": "休息不是浪费时间。"},
     {"career": "倦怠期延长，提不起劲。",
      "relationship": "冷淡期太久。",
      "health": "卧床过度，开始难起。",
      "growth": "休息的下一程是重新进入。"}),
    (54, "宝剑五", "Five of Swords",
     ["惨胜", "争吵后的空虚", "失败的赢"],
     "握三剑的胜者背景两人垂头——赢了但失了什么。",
     {"career": "争得了利益但失了同事关系。",
      "relationship": "吵赢了那个谁对但关系冷下来。",
      "health": "用极端方法达成目标但伤了底子。",
      "growth": "问问：这场仗值吗？"},
     {"career": "终于愿意和解、低头。",
      "relationship": "放下我对你错。",
      "health": "停止苛待身体。",
      "growth": "原谅自己当时的好胜。"}),
    (55, "宝剑六", "Six of Swords",
     ["过渡", "离开", "渡向彼岸"],
     "船上的人渡水离开——伤虽未尽，方向已定。",
     {"career": "离开旧工作走向新方向，过渡期。",
      "relationship": "离开一段不健康的关系。",
      "health": "走出病症的低谷期。",
      "growth": "你正在路上，岸还没到。"},
     {"career": "想走却走不掉。",
      "relationship": "拖着不离开。",
      "health": "康复反复，停滞。",
      "growth": "桨在你手里。划。"}),
    (56, "宝剑七", "Seven of Swords",
     ["欺骗", "暗中行动", "策略性回避"],
     "悄悄拿五剑离去的人——以巧避正面。",
     {"career": "可能被同事抢功，或者你在用迂回方式达成。",
      "relationship": "对方在隐瞒，或你在隐瞒。",
      "health": "对身体的真实状况打折扣。",
      "growth": "策略可以聪明，但别变狡猾。"},
     {"career": "终于决定坦白、公开行事。",
      "relationship": "真相被揭开。",
      "health": "面对自己一直藏着不报的症状。",
      "growth": "诚实比聪明更长久。"}),
    (57, "宝剑八", "Eight of Swords",
     ["自我设限", "被困", "实则可走"],
     "蒙眼绑住的人被剑包围——其实绳松。",
     {"career": "感觉被职业困住，但你比自己以为的有更多选择。",
      "relationship": "感到无路可走，其实可以离开。",
      "health": "认为某个习惯改不掉，其实只是没真的试。",
      "growth": "看清你给自己设的限。"},
     {"career": "终于解开自我设限。",
      "relationship": "意识到自己一直可以走。",
      "health": "开始打破长期被认为改不了的习惯。",
      "growth": "你一直是自由的。"}),
    (58, "宝剑九", "Nine of Swords",
     ["焦虑", "失眠", "深夜的恐惧"],
     "床上坐起的人掩面，九剑挂墙——脑中的恐惧。",
     {"career": "工作焦虑到失眠。",
      "relationship": "关于关系的灾难化想象。",
      "health": "焦虑躯体化——心悸、失眠、噩梦。",
      "growth": "区分真实威胁和脑中风暴。"},
     {"career": "焦虑开始消退，看清那只是脑造的。",
      "relationship": "走出关于关系的灾难化。",
      "health": "失眠改善。",
      "growth": "那些半夜的恐惧大多不是真的。"}),
    (59, "宝剑十", "Ten of Swords",
     ["谷底", "彻底失败", "结束才能开始"],
     "倒地的人背插十剑，黎明在地平线——最坏已过。",
     {"career": "一次彻底的失败。但也意味着不可能更糟。",
      "relationship": "关系到了最坏的一天。",
      "health": "身体到了崩溃点。",
      "growth": "谷底的好处是只能向上。"},
     {"career": "缓慢重建。",
      "relationship": "复合或彻底放下。",
      "health": "康复路上。",
      "growth": "废墟之上盖新房。"}),
    (60, "宝剑侍从", "Page of Swords",
     ["好奇的提问者", "学习", "锐意"],
     "持剑站风中的青年——思维的锋芒初露。",
     {"career": "学习新技能、新工具。",
      "relationship": "需要直接的问答而非含蓄。",
      "health": "查资料了解自己的状况。",
      "growth": "保持提问者的姿态。"},
     {"career": "话多但不深，或者爱当杠精。",
      "relationship": "嘴利伤人。",
      "health": "知识半懂半不懂，乱用。",
      "growth": "锋利之前先成熟。"}),
    (61, "宝剑骑士", "Knight of Swords",
     ["快速行动", "直冲", "敢说敢做"],
     "白马疾驰挥剑的骑士——思维转为行动的速度。",
     {"career": "雷厉风行的项目推进者。",
      "relationship": "直接、不拐弯的关系。",
      "health": "干净利落地改习惯。",
      "growth": "果决的力量。"},
     {"career": "鲁莽冲撞、不顾后果。",
      "relationship": "言辞过激伤人。",
      "health": "极端运动或饮食。",
      "growth": "速度需要刹车。"}),
    (62, "宝剑圣母", "Queen of Swords",
     ["清晰独立", "锋利的智慧", "经历后的冷静"],
     "王座女性持剑向天——经验淬出的思辨。",
     {"career": "你的判断力是团队的稳定器。",
      "relationship": "你能说出别人不敢说的真相。",
      "health": "理性管理身体。",
      "growth": "经历给了你清晰，不是冷漠。"},
     {"career": "苛刻、孤立、用智力压人。",
      "relationship": "用言语武器化。",
      "health": "理性过头，否认情感的影响。",
      "growth": "智慧需要温度。"}),
    (63, "宝剑国王", "King of Swords",
     ["公正的智者", "原则的领导", "清晰的判断"],
     "正坐王座，剑直立——心智之父。",
     {"career": "决策权交到你手上，你能公正使用。",
      "relationship": "成熟的对话，原则清晰。",
      "health": "用知识系统地照顾自己。",
      "growth": "你已经是那个能给出忠告的人。"},
     {"career": "权力变成专横，原则变成教条。",
      "relationship": "用理性回避情感。",
      "health": "对身体过度理性化。",
      "growth": "原则不是冷漠。"}),
]


# ── PENTACLES (Earth / Material) — ids 64-77 ──
PENTACLES = [
    (64, "星币一", "Ace of Pentacles",
     ["物质机会", "新资源", "种子落地"],
     "云中之手托一枚金星币——丰盛的实在开端。",
     {"career": "新工作、加薪、投资机会出现。落地型的好机会。",
      "relationship": "关系进入有现实基础的阶段——同居、共同购置。",
      "health": "身体打下新的健康基础。",
      "growth": "把愿景兑现成可触的东西。"},
     {"career": "机会到手没把握住，或来了个看似好其实虚的。",
      "relationship": "用物质替代情感投入。",
      "health": "投入资源到身体上但方法错。",
      "growth": "种子没种好就期待收成。"}),
    (65, "星币二", "Two of Pentacles",
     ["平衡多任务", "灵活", "双手抛接"],
     "舞者抛接两枚星币，无穷符号缠绕——动态平衡。",
     {"career": "同时handle 多个项目。能力够，需要节奏。",
      "relationship": "工作与关系的时间平衡。",
      "health": "工作与休息的张弛。",
      "growth": "平衡是一直在调整的过程。"},
     {"career": "球掉了——某一边失衡。",
      "relationship": "顾不上另一半。",
      "health": "节奏混乱，身体在抗议。",
      "growth": "承认抛不了那么多球。"}),
    (66, "星币三", "Three of Pentacles",
     ["合作", "技艺被认可", "工匠精神"],
     "工匠在教堂施工被两位顾问欣赏——专业被见证。",
     {"career": "在团队中你的专业被认可，跨职能合作顺畅。",
      "relationship": "一起做一个共同项目(装修、孩子、生意)。",
      "health": "和专业人士(医生、教练)合作。",
      "growth": "学会接受指点。"},
     {"career": "团队配合失调，或者你的专业被低估。",
      "relationship": "在共同项目上意见冲突。",
      "health": "对专业建议执行不到位。",
      "growth": "傲慢挡住了精进。"}),
    (67, "星币四", "Four of Pentacles",
     ["守财", "稳固", "握紧"],
     "坐者紧抱四枚星币——稳但僵。",
     {"career": "握紧已有的位置，不愿冒险。",
      "relationship": "占有欲明显，怕失去对方。",
      "health": "节制到囤积——比如囤食、囤补品。",
      "growth": "握紧的代价是不能伸手。"},
     {"career": "终于愿意放手投资或冒险。",
      "relationship": "放下占有，给关系空气。",
      "health": "停止囤积式的安全感补偿。",
      "growth": "松手才能再持。"}),
    (68, "星币五", "Five of Pentacles",
     ["匮乏", "失业", "被排除在外"],
     "雪夜中两个穷人路过亮灯的教堂——救助在咫尺却看不见。",
     {"career": "失业、收入吃紧、被排除在外。",
      "relationship": "感到被冷落、不被支持。",
      "health": "身体的痛被忽略，或没有医疗资源。",
      "growth": "求助不丢人。教堂就在那里。"},
     {"career": "走出经济低谷。",
      "relationship": "找到支持系统。",
      "health": "获得需要的医疗。",
      "growth": "你不再是一个人。"}),
    (69, "星币六", "Six of Pentacles",
     ["给予与接受", "慷慨", "天平的两端"],
     "富者持天平派币给乞者——流动的善意。",
     {"career": "你在给予帮助，或被给予帮助。",
      "relationship": "关系里施与受的平衡。",
      "health": "接受家人朋友的支持。",
      "growth": "给和受都是连接。"},
     {"career": "施舍带优越感，或受时带羞愧。",
      "relationship": "一方一直给，一方一直受。",
      "health": "拒绝接受帮助。",
      "growth": "天平需要两端都在。"}),
    (70, "星币七", "Seven of Pentacles",
     ["耐心耕耘", "评估投入", "中场反思"],
     "农夫倚锄看葡萄藤上六币——已有进展但需等待。",
     {"career": "项目进展到中场，停下评估再决定下一步。",
      "relationship": "关系到了一个该看一看走向的点。",
      "health": "评估健康计划的实际效果。",
      "growth": "耐心不是被动。"},
     {"career": "投入回报失衡。",
      "relationship": "投入越多越觉得不值。",
      "health": "方法不对，回报与投入不成比例。",
      "growth": "重新评估值不值。"}),
    (71, "星币八", "Eight of Pentacles",
     ["精进", "工匠时刻", "反复打磨"],
     "工匠专心雕刻星币——技艺的纯熟阶段。",
     {"career": "进入深度精进阶段，一项技能反复打磨。",
      "relationship": "为关系反复做小的努力。",
      "health": "建立日复一日的健康习惯。",
      "growth": "好的成果是无聊的重复。"},
     {"career": "为细节焦虑而看不见大方向。",
      "relationship": "为关系做了很多但没在对的方向上。",
      "health": "强迫式锻炼，失去乐趣。",
      "growth": "精进需要灵魂，不只是手。"}),
    (72, "星币九", "Nine of Pentacles",
     ["独立丰盛", "自给自足", "花园里的女主人"],
     "葡萄园中女性手栖鹰——经济与心灵的独立。",
     {"career": "财务独立的阶段，可以挑选要做什么。",
      "relationship": "你不需要谁也能过得好——所以遇见的人更对。",
      "health": "在自己的节奏里维护身体。",
      "growth": "独立不是孤立。"},
     {"career": "财务依赖让你失去话语权。",
      "relationship": "经济依赖导致感情失衡。",
      "health": "为了别人的期待生活。",
      "growth": "重建自己的根。"}),
    (73, "星币十", "Ten of Pentacles",
     ["家业", "传承", "几代同堂"],
     "老者、家庭、犬、十币排成生命树——丰盛的代际。",
     {"career": "建立可传承的业务、知识、声誉。",
      "relationship": "为下一代/家族考虑的阶段。",
      "health": "为家族健康史负责。",
      "growth": "你做的事会比你活得更长。"},
     {"career": "家族财富/期望成包袱。",
      "relationship": "为了家庭压住自己的选择。",
      "health": "忽视个人健康为照顾家人。",
      "growth": "传承不必复制。"}),
    (74, "星币侍从", "Page of Pentacles",
     ["专注的学徒", "新技能", "认真学习"],
     "持币凝视的年轻人——务实的开端。",
     {"career": "新岗位、新技能学习，认真打底。",
      "relationship": "认真对待一段新关系，从小事做起。",
      "health": "学习一个新的健康方法。",
      "growth": "学徒姿态最长。"},
     {"career": "学得慢、跟不上节奏。",
      "relationship": "对关系投入不足。",
      "health": "三天打鱼两天晒网。",
      "growth": "学徒之路需要持续。"}),
    (75, "星币骑士", "Knight of Pentacles",
     ["稳步推进", "可靠", "缓慢但不停"],
     "重型马上的骑士手持星币——慢但稳。",
     {"career": "稳扎稳打的执行者。可能慢但绝不出错。",
      "relationship": "可靠不浪漫的伴侣。",
      "health": "缓慢但持续的健康改善。",
      "growth": "进步不必快，但要不停。"},
     {"career": "停滞、固执、对新事物抗拒。",
      "relationship": "无聊到关系停滞。",
      "health": "习惯老化，没新刺激。",
      "growth": "稳定不等于不动。"}),
    (76, "星币圣母", "Queen of Pentacles",
     ["实际的滋养", "财务的智慧", "兼顾内外"],
     "户外王座的女性怀抱星币——能扛实务的母性。",
     {"career": "你能同时管事业和家庭。",
      "relationship": "你给关系提供物质和情感的双重支持。",
      "health": "用实在的方法(运动、饮食、医生)照顾自己和家人。",
      "growth": "你能落地。"},
     {"career": "事业和家庭一起拖垮你。",
      "relationship": "为家庭牺牲事业，反过来又怨。",
      "health": "扛太多病倒。",
      "growth": "你不必扛起所有人。"}),
    (77, "星币国王", "King of Pentacles",
     ["物质丰盛", "稳固成就", "土地之主"],
     "王座之主手持币与权杖，葡萄藤围绕——物质王国的智者。",
     {"career": "你已经建立起可见的业绩与财富。",
      "relationship": "提供安稳的生活基础。",
      "health": "成熟管理身体。",
      "growth": "你已经证明给自己看了。"},
     {"career": "对物质的执着压过其他价值。",
      "relationship": "用钱解决关系问题。",
      "health": "对身体过度物质化的对待——只看数据不看感受。",
      "growth": "成功之后下一程是给意义。"}),
]


def main() -> None:
    existing = json.loads(CORPUS_PATH.read_text(encoding="utf-8"))
    seen = {(e["card_id"], e["orientation"]) for e in existing}
    additions = []
    for suit in (CUPS, SWORDS, PENTACLES):
        for entry in expand_suit(suit):
            key = (entry["card_id"], entry["orientation"])
            if key not in seen:
                additions.append(entry)
                seen.add(key)
    combined = existing + additions
    print(f"existing: {len(existing)}, adding: {len(additions)}, final: {len(combined)}")
    CORPUS_PATH.write_text(
        json.dumps(combined, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
